// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawlyPetCare.Infrastructure;

#nullable disable

namespace PawlyPetCare.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203081523_UpdatePetSeedData")]
    partial class UpdatePetSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.AdoptionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("AdoptionRequests");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Excerpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Main Health Plaza, Suite 400",
                            City = "New York",
                            Description = "World-Class Care For Your Best Friend. Specialized veterinarians, modern equipment, and 24/7 care.",
                            Name = "Pawly Main Clinic",
                            PhoneNumber = "+1 (555) 123-4567",
                            State = "NY",
                            ZipCode = "11201"
                        });
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = "Mon,Wed,Fri,Sat",
                            ClinicId = 1,
                            ExperienceYears = 15,
                            Image = "https://img.freepik.com/free-photo/close-up-health-worker_23-2149112506.jpg?t=st=1769968108~exp=1769971708~hmac=776163d86f26ae815d19154eb6dbe230a0e53b173b9720bffdc9e4a243b970a1",
                            Location = "Pawly Main Clinic",
                            Name = "Dr. Richard Hamilton",
                            Rating = 4.9000000000000004,
                            Specialty = "Senior Veterinary Surgeon"
                        },
                        new
                        {
                            Id = 2,
                            Availability = "Tue,Thu,Fri",
                            ClinicId = 1,
                            ExperienceYears = 10,
                            Image = "https://img.freepik.com/free-photo/female-doctor-hospital-with-stethoscope_23-2148827776.jpg?semt=ais_hybrid&w=740&q=80",
                            Location = "Pawly Main Clinic",
                            Name = "Dr. Isabella Rossi",
                            Rating = 5.0,
                            Specialty = "Dermatology & Allergy Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Availability = "Mon,Tue,Thu",
                            ClinicId = 1,
                            ExperienceYears = 12,
                            Image = "https://img.freepik.com/free-photo/close-up-health-worker_23-2149112576.jpg?t=st=1769968157~exp=1769971757~hmac=cef906f5b4c3c4931da10ccbb42c3abb3f1dbff106c2d5b7b947cd2fc315c042",
                            Location = "Pawly Main Clinic",
                            Name = "Dr. James Sterling",
                            Rating = 4.7999999999999998,
                            Specialty = "Dental & Oral Surgery"
                        },
                        new
                        {
                            Id = 4,
                            Availability = "Wed,Sat,Sun",
                            ClinicId = 1,
                            ExperienceYears = 9,
                            Image = "https://img.freepik.com/free-photo/portrait-beautiful-young-female-doctor_329181-1163.jpg?t=st=1769968709~exp=1769972309~hmac=f14363b73f0cfa29201dfd812bb25548db7a9596a4630cccf38494b50bd498cf&w=1480",
                            Location = "Pawly Main Clinic",
                            Name = "Dr. Elena Petrova",
                            Rating = 4.9000000000000004,
                            Specialty = "Exotic Animal Specialist"
                        });
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Golden Retriever",
                            CreatedAt = new DateTime(2026, 2, 3, 8, 15, 23, 12, DateTimeKind.Utc).AddTicks(3328),
                            Description = "Max is a happy-go-lucky Golden Retriever who loves to swim and play fetch.",
                            Gender = "Male",
                            Image = "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=800",
                            Location = "Cairo, Egypt",
                            Name = "Max",
                            OwnerEmail = "adopt@pawly.com",
                            OwnerPhone = "+1 (555) 010-1010",
                            Size = "Large",
                            Status = "Approved",
                            Traits = "Friendly, Energetic, Loyal",
                            Type = "Dog",
                            Weight = "30kg"
                        },
                        new
                        {
                            Id = 2,
                            Age = 1,
                            Breed = "Persian",
                            CreatedAt = new DateTime(2026, 2, 3, 8, 15, 23, 12, DateTimeKind.Utc).AddTicks(5483),
                            Description = "Luna is a beautiful Persian cat with a very sweet and quiet personality.",
                            Gender = "Female",
                            Image = "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800",
                            Location = "Alexandria, Egypt",
                            Name = "Luna",
                            OwnerEmail = "adopt@pawly.com",
                            OwnerPhone = "+1 (555) 020-2020",
                            Size = "Small",
                            Status = "Approved",
                            Traits = "Calm, Gentle, Affectionate",
                            Type = "Cat",
                            Weight = "4kg"
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Breed = "German Shepherd",
                            CreatedAt = new DateTime(2026, 2, 3, 8, 15, 23, 12, DateTimeKind.Utc).AddTicks(5490),
                            Description = "Rocky is a highly intelligent German Shepherd who needs an active home.",
                            Gender = "Male",
                            Image = "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&q=80&w=800",
                            Location = "Giza, Egypt",
                            Name = "Rocky",
                            OwnerEmail = "adopt@pawly.com",
                            OwnerPhone = "+1 (555) 030-3030",
                            Size = "Large",
                            Status = "Approved",
                            Traits = "Protective, Intelligent, Active",
                            Type = "Dog",
                            Weight = "35kg"
                        },
                        new
                        {
                            Id = 4,
                            Age = 4,
                            Breed = "Beagle",
                            CreatedAt = new DateTime(2026, 2, 3, 8, 15, 23, 12, DateTimeKind.Utc).AddTicks(5493),
                            Description = "Milo is a classic Beagle who loves sniffing out new adventures.",
                            Gender = "Male",
                            Image = "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&q=80&w=800",
                            Location = "Cairo, Egypt",
                            Name = "Milo",
                            OwnerEmail = "adopt@pawly.com",
                            OwnerPhone = "+1 (555) 040-4040",
                            Size = "Medium",
                            Status = "Approved",
                            Traits = "Playful, Curious, Happy",
                            Type = "Dog",
                            Weight = "12kg"
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            Breed = "Siamese",
                            CreatedAt = new DateTime(2026, 2, 3, 8, 15, 23, 12, DateTimeKind.Utc).AddTicks(5495),
                            Description = "Bella is a social Siamese cat who loves to be the center of attention.",
                            Gender = "Female",
                            Image = "https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=800",
                            Location = "Mansoura, Egypt",
                            Name = "Bella",
                            OwnerEmail = "adopt@pawly.com",
                            OwnerPhone = "+1 (555) 050-5050",
                            Size = "Small",
                            Status = "Approved",
                            Traits = "Vocal, Smart, Social",
                            Type = "Cat",
                            Weight = "3.5kg"
                        },
                        new
                        {
                            Id = 6,
                            Age = 1,
                            Breed = "Poodle",
                            CreatedAt = new DateTime(2026, 2, 3, 8, 15, 23, 12, DateTimeKind.Utc).AddTicks(5498),
                            Description = "Charlie is a charming little poodle who is great with children.",
                            Gender = "Male",
                            Image = "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=800",
                            Location = "Cairo, Egypt",
                            Name = "Charlie",
                            OwnerEmail = "adopt@pawly.com",
                            OwnerPhone = "+1 (555) 060-6060",
                            Size = "Small",
                            Status = "Approved",
                            Traits = "Hypoallergenic, Elegant, Fun",
                            Type = "Dog",
                            Weight = "6kg"
                        });
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@pawly.com",
                            IsVerified = true,
                            Name = "Admin User",
                            PasswordHash = "admin",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.AdoptionRequest", b =>
                {
                    b.HasOne("PawlyPetCare.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawlyPetCare.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("PawlyPetCare.Domain.Entities.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("PawlyPetCare.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("PawlyPetCare.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
